### PR TITLE
LPS-WEE

### PR DESCRIPTION
**Pull request by sandrodw3**
As Sandro, I want to use "Weee" as commit message

### CODE REVIEW

**Comment by jbalsas** [comment]
Esto os parece una manera seria de programar?

Ni descripción en la PR, ni en los commits... 

shame

**Comment by p2kmgcl** [comment]
https://github.com/p2kmgcl/page-editor-dev-server/commit/fd68e6a7c4b0ee5353c2781e949cbedc2322ab71

**Comment by jbalsas** [comment]
stopit

**Comment by victorg1991** [comment]
Super WEEEEll done

**Pull request merged**
